### ISSUE TITLE
Increase page size for azure windows agents?

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-forge-ci-setup-feedstock#155]
After often encountering 
```
OSError: [WinError 1455] The paging file is too small for this operation to complete
```
in https://github.com/conda-forge/numpy-feedstock/pull/237 & many other pull requests (for numpy), I decided to have a quick look at what's behind that.

Stumbling over this [discussion](https://github.community/t/error-the-paging-file-is-too-small-for-this-operation-to-complete/17141) (regarding GH Actions), someone noted:
> I’ve investigated this issue and the problem is that Windows decides to create a single page file on the D:\ drive, which has only 14 GB, and by default it allocates only 1/8th of the volume size, or about 1.75 GB. This is a very small page file by modern standards and many applications will fail.

How about adding an option (or step) to the ci-setup that allows setting the page file size? It seems to be possible for GHAs - someone [published](https://github.com/actions/virtual-environments/issues/785#issuecomment-625705010) an [action](https://github.com/al-cheb/configure-pagefile-action) for it (it's MIT licensed so we could even reuse some of that code).

**Comment by isuruf** [comment]
PRs welcome. I don't think we need an option for this. Doing this unconditionally makes sense.

**Comment by isuruf** [comment]
Wait, maybe only if CONDA_BLD_PATH is set to C://bld//

**Comment by h-vetinari** [comment]
Core of such a PR would IMO be copying [`SetPageFileSize.ps1`](https://github.com/al-cheb/configure-pagefile-action/blob/master/scripts/SetPageFileSize.ps1) and calling it from `run_conda_forge_build_setup_win.bat` appropriately (i.e. if-cond & params) - would you want that in `recipe/` or `recipe/conda_forge_ci_setup` or elsewhere?

**Comment by isuruf** [comment]
In recipe is fine.

**Comment by h-vetinari** [comment]
See #156
