### ISSUE TITLE
old version getting pulled

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge-ci-setup-feedstock#177]
Over in https://github.com/conda-forge/fftw-feedstock/pull/81 it appears that the version right before we added the boa run constraint is getting pulled. IDK why but it is causing errors for cross-compiled builds. 

cc @conda-forge/core @wolfv @isuruf

**Comment by isuruf** [comment]
conda is trying to maximize the version of boa which 0.8 and that downgrades `conda-forge-ci-setup`.

**Comment by beckermr** [comment]
Ahhhh - I'll make a PR to repin or maybe we remove it all together?

**Comment by isuruf** [comment]
Or patch the older versions of conda-forge-ci-setup to have the same run_constrained as well.

**Comment by beckermr** [comment]
Right. If we patch everything to have the same value always, then it will always work.

**Comment by beckermr** [comment]
Let's merge the PR above for now and defer a real fix. I can't decide. If you have strong opinions, let's go with that.

**Comment by beckermr** [comment]
Saw your other comment. I will hotfix later.
