### ISSUE TITLE
reduce build matrix since the addition of CUDA testing

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge-ci-setup-feedstock#191]
The inclusion of CUDA in the build matrix to make sure things are tested has caused some weird solver features where packages at the same build number and version are swapped back and forth. 

This is annoying and there are a couple of solutions.

1. Prioritize the cuda None builds via build number
2. Test each CUDA version in a different python version (suggestion by @hmaarrfk)

We should do one of these likely.

**Comment by jakirkham** [comment]
cc @jaimergp

**Comment by beckermr** [comment]
Yeah looking at the suggestions now, I think we have to go with 1 above. 

My worry is that as we drop python versions, we will drop CUDA tests. Even worse, as we drop CUDA versions, we may drop whole python versions (!!) by accident. This means we have to make manual changes every time we make an edit to the global build matrix. I don't want to maintain that and I know we will forget. For example, when we added python 3.10, we did not update the static migrators in the build on master now and thus the feedstock was broken until I figured out what was going on.

A third option would be to add an option to the ci scripts setup package to not upload certain outputs. This could be useful in a lot of places besides this one, but is also work to maintain.

@hmaarrfk Would you be OK with the build number prioritization instead?

**Comment by hmaarrfk** [comment]
ok with me!

**Comment by beckermr** [comment]
Awesome! This is in my current PR so I we can go with that. Thanks for being flexible on this!

**Comment by beckermr** [comment]
closed in #190
