### ISSUE TITLE
Incorrect detection of more than one build number

### ISSUE THREAD

**Issue by benbovy** [conda-forge/conda-forge-ci-setup-feedstock#25]
xref https://github.com/conda/conda-build/issues/3095

I'm posting this here too since I'm not sure where this should be fixed.

An easy workaround would be to ensure that build numbers are `int` here:

https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/cfee5c07bf0559bf36372174e71c41eeb207a169/recipe/conda_forge_ci_setup/build_utils.py#L123

but maybe it's better to fix this in conda-build.

**Comment by hmaarrfk** [comment]
I've been dealing with this issue too trying to develop this recipe here

https://github.com/conda-forge/sqlite-feedstock/pull/32

A few lines below, it is cast as an int anyway

https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/cfee5c07bf0559bf36372174e71c41eeb207a169/recipe/conda_forge_ci_setup/build_utils.py#L127

Seems safe to do the casting before :cactus:

**Comment by msarahan** [comment]
Everything in conda-build is treated as a string.  Conda-build does no type-conversion when you use get_value.  You should do it on the conda-smithy side if you need it.
