### ISSUE TITLE
Sporadic CI error: `conda-forge-ci-setup 3**  does not exist` ?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-ci-setup-feedstock#262]
Saw the following error [on CI]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=768085&view=logs&j=52410884-a307-50a4-0724-2831dfb662ff&s=96ac2280-8cb4-5df5-99de-dd2da759617d&t=71b6080f-100f-5cd5-ba7f-0c01a4bc74c7&l=24 ) (also the [attached log]( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/files/12432445/xgboost-feedstock_20230824.1_linux_aarch64_c_compiler_version10cuda_compilernvcccxx_compiler_version10.txt )):

```python
+ mamba install --update-specs --yes --quiet --channel conda-forge conda-build pip boa conda-forge-ci-setup=3
Could not solve for environment specs
The following package could not be installed
└─ conda-forge-ci-setup 3**  does not exist (perhaps a typo or a missing channel).
```

Note: Other jobs in the same build did not see this issue

**Comment by h-vetinari** [comment]
Seeing this on the openjdk feedstock ATM, but only on the aarch/ppc builds, and not always either:
* https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=775477&view=results (2 jobs fail)
* https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=775478&view=results (1 job fails)
* https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=775018&view=results (0 jobs fail)
