### ISSUE TITLE
Support MACOSX_SDK_VERSION 13.3

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/conda-forge-ci-setup-feedstock#264]
### Comment:

When XCode [15.0 final](https://xcodereleases.com/) drops, it should be possible to support `MACOSX_SDK_VERSION: "13.3"`.

References:
- https://github.com/conda-forge/spidermonkey-feedstock/pull/11#issuecomment-1692277042

**Comment by h-vetinari** [comment]
It's possible that spidermonkey has this check built-in for requiring certain C++ features from newer SDKs, which we however could provide through `libcxx` and [`_LIBCPP_DISABLE_AVAILABILITY`](https://conda-forge.org/docs/maintainer/knowledge_base.html#newer-c-features-with-old-sdk). If so, it'd just be a matter of patching out the check.

Generally, the SDK would be needed for three reasons:
* compilers
* C++ stdlib
* C stdlib

The first we always provide ourselves, the second we can through the above, and only the third is basically impossible to change (but will be possible to specify at least using a mechanism like https://github.com/conda-forge/staged-recipes/pull/23777)

**Comment by bollwyvl** [comment]
I was going off 1) that failure and 2) the [official guidance](https://firefox-source-docs.mozilla.org/widget/cocoa/sdks.html#supported-sdks)... doesn't _really_ matter to me either way, and I'm not in a particular hurry.

**Comment by bollwyvl** [comment]
Looks like today (or a few days ago) is that day: #281

**Comment by bollwyvl** [comment]
I didn't bump the build/version, so looks like this didn't deploy yet...

**Comment by jakirkham** [comment]
Could bump the version (if that hasn't already happened in a subsequent PR)
