### ISSUE TITLE
`validate_recipe_outputs` failing due to missing `conda_build.config.subdir` (conda-build 24.5.0?)

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-ci-setup-feedstock#317]
Seeing the following error in [this CI log]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=933386&view=logs&jobId=656edd35-690f-5c53-9ba3-09c10d0bea97&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3 ) (also [attached log]( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/files/15301031/cuda-sanitizer-api-feedstocklinux_64_20240513.1_.txt )):

```python
+ validate_recipe_outputs cuda-sanitizer-api-feedstock
Traceback (most recent call last):
  File "/opt/conda/bin/validate_recipe_outputs", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/conda_forge_ci_setup/feedstock_outputs.py", line 165, in main
    for p in os.listdir(os.path.join(conda_build.config.croot, conda_build.config.subdir))  # noqa
  File "/opt/conda/lib/python3.10/site-packages/conda_build/deprecations.py", line 301, in __getattr__
    raise AttributeError(f"module '{fullname}' has no attribute '{name}'")
AttributeError: module 'conda_build.config' has no attribute 'subdir'
```

Relevant code paths:

https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/3b9904b4213a7fe442588d66bca4651ef92aeacd/recipe/conda_forge_ci_setup/feedstock_outputs.py#L164-L165

**Comment by jakirkham** [comment]
Am seeing this in all other recent builds (for [example]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=933331&view=results ))

Think we may want to pull `conda-build` version `24.5.0` or constrain our tooling until we have an opportunity to fix this properly

cc @conda-forge/core

**Comment by jakirkham** [comment]
Actually maybe we just need this fix extended ( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/305 )?

**Comment by jakirkham** [comment]
Pushed a potential fix: https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/318

Though it is possible that it also won't deploy until this issue is resolved

So think we still will need to mark broken `conda-build` version `24.5.0` (possibly also `conda` version `24.5.0`). Then review and deploy the fix. And then mark unbroken `conda` & `conda-build` version `24.5.0`

**Comment by beckermr** [comment]
It will deploy. The feedstock here uses the local copy of ci setup to bootstrap properly.

**Comment by jakirkham** [comment]
Know that is true of some scripts, but wasn't sure whether that was true of package validation

In any event happy to try the fix first

If we are still seeing issues, think we should just mark `conda` & `conda-build` version `24.5.0` broken for now and revisit in the morning. Put together a PR to do that: https://github.com/conda-forge/admin-requests/pull/995

**Comment by beckermr** [comment]
It's true of everything provided by ci setup.

**Comment by beckermr** [comment]
Well shit the bootstrapping is broken again. Wtf? Will fix by hand.

**Comment by beckermr** [comment]
It's not the bootstrapping. We missed more old apis. I'll push a new pr.

**Comment by jakirkham** [comment]
From [CI]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=933427&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642 ):

```python
Traceback (most recent call last):
  File "/opt/conda/bin/upload_package", line 8, in <module>
    sys.exit(upload_package())
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/conda_forge_ci_setup/build_utils.py", line 247, in upload_package
    retry_upload_or_check(
  File "/opt/conda/lib/python3.10/site-packages/conda_forge_ci_setup/upload_or_check_non_existence.py", line 349, in retry_upload_or_check
    raise TimeoutError("Did not manage to upload package.  Failing.")
TimeoutError: Did not manage to upload package.  Failing.
```

**Comment by jakirkham** [comment]
Submitted PR: https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/319

Not seeing any others of this form

If there are different issues, we may need to talk to others familiar with the upstream deprecations

**Comment by jakirkham** [comment]
Am seeing [new builds on `main`]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=933466&view=results ) starting to pass. So think this is resolving itself

**Comment by jakirkham** [comment]
For tracking/visibility, filed a status issue: https://github.com/conda-forge/status/issues/177

**Comment by jaimergp** [comment]
Thank you both! <3
