### ISSUE TITLE
Handle Azure in CI fast finish script

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-ci-setup-feedstock#32]
Currently [the fast finish script]( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/master/recipe/ff_ci_pr_build.py ) doesn't handle fast finishing jobs on Azure. We should update it to handle that case. This will require using some API to see what jobs are running for a PR and seeing where are job ranks in that list (canceling if it is not the newest entry).

cc @DavidStaheli

xref: https://github.com/conda-forge/conda-smithy/pull/901#discussion_r228598919

**Comment by mariusvniekerk** [comment]
Since azure cancels jobs that have been superseded, im closing this
