### ISSUE TITLE
Download macOS SDK 10.9 if missing generally

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-ci-setup-feedstock#33]
Would be good to update the check here to handle downloading the macOS 10.9 SDK generally if it is missing (as opposed to checking CircleCI specifically). Should make this work more generally on different providers with different offerings.

**Comment by timsnyder** [comment]
Is this still a legit issue?  where is 'here' in 'the check here'?

**Comment by jakirkham** [comment]
Thanks for the reminder. No I think this was solved in PR ( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/31 ) sometime ago. This should have been closed.

Yeah the check use to check for CircleCI. That is no longer the case.
