### ISSUE TITLE
Output validation fails when there are downstream tests

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-forge-ci-setup-feedstock#342]
When there are downstreams tests, conda-build downloads the outputs to the same folder that the built packages are.

For example see https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/1028622/logs/45
This fails because cython and setuptools are in https://github.com/conda-forge/python-feedstock/blob/main/recipe/meta.yaml#L184-L187

**Comment by isuruf** [comment]
cc @beckermr

**Comment by beckermr** [comment]
ahhh I missed this! Let me take a look.

**Comment by beckermr** [comment]
I know how to fix. Will push a PR in a bit. Sorry for the trouble!

**Comment by h-vetinari** [comment]
Still fails in libcxx even after #344 (post-merge for https://github.com/conda-forge/libcxx-feedstock/pull/195)
```
validation results:
{
  "osx-64/libcxx-testing-0.18.99-h33f3928_1.conda": false,
  "osx-64/libcxx-testing-0.16.99-he7e073f_1.conda": false,
  "osx-64/libcxx-devel-19.1.0-h7c275be_0.conda": true,
  "osx-64/libcxx-19.1.0-hf95d169_0.conda": true,
  "osx-64/libcxx-testing-0.17.99-ha468150_1.conda": false
}
NOTE: Any outputs marked as False are not allowed for this feedstock. See https://conda-forge.org/docs/maintainer/infrastructure/#output-validation-and-feedstock-tokens for information on how to address this error.
```

**Comment by beckermr** [comment]
That job pulled in an old version

> conda-forge-ci-setup      4.9.1           py312hd35cd3b_100    conda-forg

You need at least 4.9.3.

**Comment by h-vetinari** [comment]
I restarted the job, it still happens with:
```
conda-forge-ci-setup      4.9.3           py312hd35cd3b_100    conda-forge
```

**Comment by h-vetinari** [comment]
See https://github.com/conda-forge/libcxx-feedstock/pull/196

**Comment by beckermr** [comment]
Thanks for testing again. I think I got the bug this time and sorry for the trouble!

xref: #347

**Comment by h-vetinari** [comment]
Thanks for the quick fix and the work on this!

**Comment by h-vetinari** [comment]
Confirmed that it works for libcxx now 👍
