### ISSUE TITLE
Inspect Artifacts not reporting anything for `noarch`?

### ISSUE THREAD

**Issue by jaimergp** [conda-forge/conda-forge-ci-setup-feedstock#354]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I don't see it in the [logs](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1037648&view=logs&jobId=656edd35-690f-5c53-9ba3-09c10d0bea97&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3) for [this PR](https://github.com/conda-forge/conda-libmamba-solver-feedstock/pull/26) in conda-libmamba-solver:

```
+ command -v inspect_artifacts
+ inspect_artifacts
Inspecting artifacts
WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
Adding in variants from internal_defaults
Adding in variants from /home/conda/feedstock_root/.ci_support/linux_64_.yaml
/opt/conda/lib/python3.10/site-packages/conda_build/environ.py:544: UserWarning: The environment variable 'SETUPTOOLS_SCM_PRETEND_VERSION' is being passed through with value '24.9.0'.  If you are splitting build and test phases with --no-test, please ensure that this value is also set similarly at test time.
  warnings.warn(
```

Should we error out if no artifacts are reported in a feedstock? That would constitute a broken build, right?

### Installed packages

```shell
--
```

### Environment info

```shell
--
```

**Comment by jaimergp** [comment]
cc @beckermr

**Comment by beckermr** [comment]
This must be a bug. I adjusted how we compute the artifacts and we may have missed noarch.
