### ISSUE TITLE
Set CPU_COUNT correctly for Azure

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-ci-setup-feedstock#47]
Currently `CPU_COUNT` is set for the previously existing CIs (i.e Travis, Circle, and AppVeyor). However to the best of my knowledge `CPU_COUNT` is likely not set correctly for Azure. Would be good to update the values set in these scripts to configure Azure correctly.

**Comment by isuruf** [comment]
https://github.com/conda-forge/conda-forge-ci-setup-feedstock/issues/53 has more discussion, so closing this as a duplicate of #53
