### ISSUE TITLE
unset CPU_COUNT for CI=drone.

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-forge-ci-setup-feedstock#57]
[This](https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/2c91fe47c7b28b5efc77dab25bab1e1d8e79cedf/recipe/run_conda_forge_build_setup_linux#L5) and [this](https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/2c91fe47c7b28b5efc77dab25bab1e1d8e79cedf/recipe/run_conda_forge_build_setup_linux#L17) has to be edited.

cc @jmreicha

**Comment by jmreicha** [comment]
My "workaround" is just to [give it more CPUs](https://github.com/conda-forge/nodejs-feedstock/blob/master/recipe/build.sh) on a per repo basis.

**Comment by isuruf** [comment]
That's not a good idea. It means I can't control the number of processors used when I build locally or in another CI. (On virtual CPUs, those values are usually wrong)

**Comment by jmreicha** [comment]
This decision was based on the feedback from the discussion in the other issue and some manual testing I did for both Travis and Drone builds, which both seem to run on bare metal.  Happy to change it back though.

**Comment by isuruf** [comment]
In the other issue, not setting `CPU_COUNT` and letting all CPUs be used was the suggestion. When you don't set the CPU_COUNT, conda-build will do what you did and figure it out automatically. But explicitly setting it in build.sh of a recipe will take flexibility away from the user.

**Comment by jmreicha** [comment]
Hmm okay, I think I must have misunderstood the direction there then.

**Comment by jmreicha** [comment]
Were you thinking something more along the lines of [this](https://github.com/jmreicha/conda-forge-ci-setup-feedstock/blob/cpu-count/recipe/run_conda_forge_build_setup_linux)?

**Comment by isuruf** [comment]
Yes

**Comment by jmreicha** [comment]
Cool, I'll go ahead and PR it then.  I didn't see you had added the CI variable to the various configs 😄

**Comment by jmreicha** [comment]
Do you think I should update for Windows and OSX as well?

**Comment by isuruf** [comment]
No, we can do that if or when that's needed.

**Comment by scopatz** [comment]
Can you provide a motivation for why this is needed?

**Comment by jmreicha** [comment]
There was some discussion [here](https://github.com/conda-forge/conda-forge.github.io/issues/269#issuecomment-489349426) about speeding up builds on Drone.  Their build servers basically have a whole bunch of cores and they are good with using as many of them as possible.

**Comment by scopatz** [comment]
Couldn't you just set `CPU_COUNT=96`, rather than unsetting it?

**Comment by jmreicha** [comment]
That's what I thought originally but @isuruf makes a good point that unsetting this gives a little more flexibility for local builds and different CI providers.

**Comment by isuruf** [comment]
Since the number of cores are going to vary between runs in the future, https://github.com/conda-forge/conda-forge.github.io/issues/269#issuecomment-489349426, it's better to unset it. We had to set this because in travis and other CI, the values for number of processors gave the value for the real hardware instead of the ones for the virtual CPUs which limits the number of processors to 2. Since in drone, the code is run on bare metal without such limitations, conda-build can figure out how many cores to use automatically.
