### ISSUE TITLE
Building locally fails, unbound variable `CI`

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-ci-setup-feedstock#63]
When running the build locally like so...

```bash
python build-locally.py <some_config_here>
```

One now sees an exception like this...

```python
+ source run_conda_forge_build_setup
/opt/conda/bin/run_conda_forge_build_setup: line 4: CI: unbound variable
Traceback (most recent call last):
  File "build-locally.py", line 58, in <module>
    main()
  File "build-locally.py", line 54, in main
    run_docker_build(ns)
  File "build-locally.py", line 19, in run_docker_build
    subprocess.check_call(script)
  File "/Users/jkirkham/miniconda/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '.azure-pipelines/run_docker_build.sh' returned non-zero exit status 1.
```

**Comment by jakirkham** [comment]
Seems to refer to [this line]( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/779840ac2af01041e4c8e83d14d385b036e09a41/recipe/run_conda_forge_build_setup_linux#L4 ), which was introduced in PR ( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/58 ).

**Comment by scopatz** [comment]
Should this be an issue on conda-smithy, which is where that script is sourced from?

**Comment by jakirkham** [comment]
I don't think so. It's referencing the `run_conda_forge_build_setup`, which comes from here.

**Comment by isuruf** [comment]
@jakirkham, can you send a PR that unsets `-u` at the beginning and resets at the end of `run_conda_forge_build_setup`

**Comment by jakirkham** [comment]
I moved that code into an existing `set +u`/`set -u` block, but should have the same affect. ( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/64 )
