### ISSUE TITLE
Conda should use newer (the newest?) OSX SDK for building

### ISSUE THREAD

**Issue by rggjan** [conda-forge/conda-forge-ci-setup-feedstock#67]
Please see the discussion here:
https://github.com/conda-forge/pyside2-feedstock/issues/46#issuecomment-563911075

Conda-forge currently builds against the OSX SDK 10.9. This causes issues for example with Qt + Pyside2, which requires both Qt and python to be built with OSX SDK 10.14 or 10.15.

I understand that Conda-forge builds against SDK 10.9 to be backwards compatible to that version of OSX. However, this is also possible with building against the newest SDK (10.15), and the setting the `deployment target` to a lower OSX version, like 10.9.

Here again the details:
> > Where did you read this? That's not how how SDKs work. You build with 10.12 and it will run on 10.14, not the other way around.
> 
> See on [developer.apple.com](https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/cross_development/Configuring/configuring.html#//apple_ref/doc/uid/10000163i-CH1-SW1):
> 
> It works both ways on OSX.
> 
> In the example of the link I posted, they build with base SDK 10.6 and run on 10.4 and newer. If the code doesn't use any of the newer API's (not existing in 10.6) this works out of the box. If the code wants to use new 10.5 or 10.6 API's on supported operating systems, the code must first check the OS version before using the API's. Which I guess Qt does, when they say on their [official docs](https://doc.qt.io/qt-5/macos.html) that compiling against the 10.14 SDK and then running on 10.12 works fine...
> 
> So Apple recommends always using the newest SDK, and then setting the `Deployment target` to the lowest OSX version you want to support...

**Comment by CJ-Wright** [comment]
xref: https://github.com/conda-forge/conda-forge.github.io/issues/891

**Comment by scopatz** [comment]
Yep, I believe that this is a duplicate

**Comment by isuruf** [comment]
It's not. conda-forge/conda-forge.github.io#891 is about packages with a requirement on newer MACOSX_DEPLOYMENT_TARGET (like 10.12). This issue is about packages with a requirement of a newer SDK, but with the same lower MACOSX_DEPLOYMENT_TARGET (like 10.9) that uses weak linking.

**Comment by scopatz** [comment]
In that case it seems like it should be moved to the conda-forge/conda-forge.github.io repo

**Comment by isuruf** [comment]
This is where the code lives, but I'm fine with either.

**Comment by scopatz** [comment]
Oh ok, nm

**Comment by rggjan** [comment]
Is there any timeline on this issue? Any way I can help?

**Comment by isuruf** [comment]
@rggjan, it looks like we can't enable this globally, but we can have an option to enable per feedstock. Issue is that most autotools based packages would check whether functions exist and using a newer SDK would make them available even if they are weak symbols. (For eg: clock_gettime is in 10.12, but autotools detects it even if target is set to 10.9 if the SDK is 10.12 or higher)

**Comment by rggjan** [comment]
I see, thanks. That makes sense.

Would it be possible to enable it for the python feedstock? As this would fix the original issue of PySide2/Qt being broken?

Should I create a separate issue for this?

**Comment by isuruf** [comment]
I suggest changing the logic at https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/master/recipe/run_conda_forge_build_setup_osx#L9-L27 to use 10.15 as the SDK if there's a variable like `WITH_LATEST_OSX_SDK` instead of using `MACOSX_DEPLOYMENT_TARGET` for the SDK version. Then we can have that variable enabled in the python-feedstock.

**Comment by rggjan** [comment]
Sounds like a good plan! However, it should be in addition to MACOSX_DEPLOYMENT_TARGET, I think. We might want to use the latest sdk, but still set MACOSX_DEPLOYMENT_TARGET to 10.9, for example, if we want the built executable to be able to run on OSX 10.9...

**Comment by rggjan** [comment]
Any updates on this? Or is there at least a way to do the same as in https://github.com/bioconda/bioconda-recipes/pull/21180 and use a newer SDK for python to fix https://github.com/conda-forge/pyside2-feedstock/issues/46?

**Comment by isuruf** [comment]
@rggjan, see my comment at https://github.com/conda-forge/conda-forge-ci-setup-feedstock/issues/67#issuecomment-596527579. PRs are welcome.

**Comment by rggjan** [comment]
Thanks a lot @psavery @isuruf!

What needs to happen to rebuild python 3.7 on OSX with these changes, so PySide2 actually works on OSX? (https://github.com/conda-forge/pyside2-feedstock/issues/46)

(Sorry, I'm not very familiar with the conda CI / building pipeline)

**Comment by cjh1** [comment]
@rggjan I think we need to raise an issue with [python-feedstock](https://github.com/conda-forge/python-feedstock), to see if they are prepared to accept setting WITH_LATEST_OSX_SDK.

**Comment by psavery** [comment]
@rggjan I put up an issue for it on the python feedstock. It is conda-forge/python-feedstock#365

**Comment by rggjan** [comment]
Perfect, thanks @psavery!

Would it make sense to do this for qt and or PySide2 as well?

**Comment by cjh1** [comment]
I think PySide2 is already be build with a newer SDK.

**Comment by rggjan** [comment]
@cjh1 How do you know?

**Comment by cjh1** [comment]
@rggjan May be not, I thought [this one](https://github.com/conda-forge/pyside2-feedstock/pull/57) had been merged, but apparently is was closed. In our testing we only needed to rebuild python.
