### ISSUE TITLE
Upload to anaconda using `--private`?

### ISSUE THREAD

**Issue by hadim** [conda-forge/conda-forge-ci-setup-feedstock#97]
Would that be possible to add this option? I need it to setup a private forge.

**Comment by hadim** [comment]
ping @beckermr

**Comment by beckermr** [comment]
Umm maybe? Idk where these options tend to go. My guess is that we need to add a config param to smithy via the conda-forge yaml and then we add a hook here that accepts a flag smithy generates for e command line.

**Comment by hadim** [comment]
Yes that the idea I think. PR can probably be made separately from `conda-smithy`.

**Comment by jakirkham** [comment]
FWIW you could override [`run_conda_forge_build_setup_linux` (or similar for other platforms)]( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/master/recipe/run_conda_forge_build_setup_linux ) in the recipe of your feedstock to do any initial setup. If this amounts to just calling `conda config`, that would be an easy way to tack it in.

**Comment by hadim** [comment]
Sorry I am not sure I understand how it will allow me to upload using a `--private` flag?

**Comment by beckermr** [comment]
These overrides may not work anymore. The way now is to copy the python package in this repo to your feedstock and make any edits you’d like. Then once you rerender smithy will use the local one.

**Comment by hadim** [comment]
Here is a backward compatible PR that accept the `--private` flag: https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/98

**Comment by hadim** [comment]
Now I am not sure what is the best way to send this `private_upload` signal from `conda-smithy`. Any idea?

**Comment by hadim** [comment]
Setting the flag to true in `recipe/conda_build_config.yaml` should do the job right? Would be nice to be able to set it in `conda-forge.yml` and render it.

**Comment by hadim** [comment]
The associated issue on the `conda-smithy` side: https://github.com/conda-forge/conda-smithy/issues/1333
